name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to allow the action to create releases and upload assets

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Compile for Windows, Linux, and macOS across AMD64 and ARM64 architectures
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Determine binary extension for Windows
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi
          
          # Build target binary
          go build -o bin/make-pdfs-editable-again-${{ matrix.goos }}-${{ matrix.goarch }}$EXT cmd/make-pdfs-editable-again/main.go

      - name: Upload Artifacts (Temporary)
        uses: actions/upload-artifact@v4
        with:
          name: make-pdfs-editable-again-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/make-pdfs-editable-again-${{ matrix.goos }}-${{ matrix.goarch }}*
          retention-days: 1

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Git Tag
        id: tag_generator
        run: |
          yyyy=$(date +%Y)
          mm=$(date +%m)
          TAG_NAME="v$yyyy.$mm.${{ github.run_number }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Download All Binaries
        uses: actions/download-artifact@v4
        with:
          path: release-binaries/
          merge-multiple: true

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_generator.outputs.tag_name }}
          files: release-binaries/*
          name: Release ${{ steps.tag_generator.outputs.tag_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
